Chat.actionbar("prepare for lift off in 3 seconds")
Client.waitTick(30)
Chat.actionbar("3")
Client.waitTick(30)
Chat.actionbar("2")
Client.waitTick(30)
Chat.actionbar("1")
Client.waitTick(30)
 Client.disconnect()